name: archeland_encyclopedia
description: 아르케랜드 사전

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter_layout_grid: ^2.0.1
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  google_mobile_ads: ^2.3.0
  google_sign_in: ^6.0.2
  go_router: ^6.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.0.2
  rxdart: ^0.27.7
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/runes/
    - assets/images/google/google-logo.png