name: archeland_encyclopedia
description: 아르케랜드 사전

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0
  go_router: ^6.0.3
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  google_sign_in: ^6.0.2
  google_mobile_ads: ^2.3.0
  rxdart: ^0.27.7
  flutter_layout_grid: ^2.0.1
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  sembast: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  riverpod_generator: ^2.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/runes/검투사.png
    - assets/images/runes/괴물늑대.png
    - assets/images/runes/구리지팡이.png
    - assets/images/runes/드래곤.png
    - assets/images/runes/마법의눈.png
    - assets/images/runes/망령기사.png
    - assets/images/runes/모래시계.png
    - assets/images/runes/설송.png
    - assets/images/runes/성검.png
    - assets/images/runes/세계수.png
    - assets/images/runes/우로보로스.png
    - assets/images/runes/전투도끼.png
    - assets/images/runes/전투마.png
    - assets/images/runes/진정한십자가.png
    - assets/images/runes/카이트실드.png
    - assets/images/runes/흡혈귀.png