name: archeland_encyclopedia
description: 아르케랜드 사전

publish_to: 'none'

version: 1.0.0+12

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter_layout_grid: ^2.0.1
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  google_mobile_ads: ^2.4.0
  google_sign_in: ^6.0.2
  go_router: ^6.5.1
  riverpod_annotation: ^2.0.2
  firebase_ui_firestore: ^1.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/runes/
    - assets/images/icons/ranger.png
    - assets/images/icons/mage.png
    - assets/images/icons/priest.png
    - assets/images/icons/tanker.png
    - assets/images/icons/warrior.png
    - assets/images/icons/shooter.png
    - assets/images/google/google-logo.png